def try_me():
    return 'success!'
